### ISSUE TITLE
JavaScript style rules that deserve tribe discussion

### ISSUE THREAD

**Issue by camhux** [simplymeasured/tribe-ui-guides#2]
Here are some rules inherited from Airbnb that I think we should talk about as a tribe before committing to.

1. I initially amended [§4.1](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#arrays--instantiation) to permit use of the `Array` constructor when creating an array of a known length, which is a rare but sometimes useful pattern that we've used in a few situations. I'd like to discuss how we feel about this amendment in general, and also whether we prefer `new Array()` to `Array()` (no new) or vice versa.
1. [§8.4](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#arrows--one-arg-parens) says it's okay to drop the parentheses around an arrow function's parameter list iff there is only one parameter _and_ if the body of the function does not use braces (single-expression). We typically always use parentheses. I'd like to discuss whether we'd be comfortable relaxing slightly to omit the parentheses in this specific case, or if we'd like to amend the rule to mandate them always.
1. [§7.1](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#functions--declarations) mandates the assignment of named function expressions to variables instead of function declaration syntax. We have typically used function declarations in our codebases, especially in module scope (as opposed to nested inside another function body, where I think assignments are more common). I want to discuss how we feel about this rule and whether to adopt it.
1. [§7.11](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#functions--signature-spacing) is related to the above. It mandates a consistent spacing scheme for function expressions appearing in the right-hand side of an assignment. I want to discuss how we feel about this rule and whether to adopt it.
1. [§7.12](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#functions--mutate-params) forbids any mutation of objects passed as parameters to a function, which is a pattern we use to decorate object instances in a handful of situations. I want to discuss the importance of this rule and whether we should retrofit our code to move away from object mutation more completely.
1. [§11.1](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#iterators--nope) bans the use of iterators, focusing on the `for ... of` ES6 syntax especially. We use this in a few places, so I want to discuss the significance of this rule and whether we should adopt it.
1. [§16.1](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#blocks--braces) permits the use of single-line blocks, ex: `if (condition) return value;`. This is banned by (I believe) our `ember-suave` linter presets. I want to discuss whether we'd like to relax our style to allow for single-line blocks, or if we'd prefer to amend this section of the style guide.
1. [§17.1](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#control-statements) is agnostic of whether multi-line compound boolean conditions should place the operators at the beginning or end of lines. I want to discuss whether we'd like to pin down a specific position for boolean operators in this situation.
1. [§19.12](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#whitespace--max-len) sets forth a max line length of 100 characters. We've historically never had any contract about max line length in our codebases. I want to discuss whether now is the time to settle on one.
1. [§23.4](https://github.com/simplymeasured/tribe-ui-guides/blob/master/javascript.md#naming--leading-underscore) forbids the use of leading underscores as a "private" hint. I want to discuss the significance of this rule, especially as it pertains to the design of certain Ember classes.

**Comment by asnider6** [comment]
Some thoughts on the points listed:

1. After looking at alternative implementations for fixed arrays in JS, it seems like using the constructor would be the lesser of evils (vs. doing something like `Object.freeze()` on the array which presents its own complication). I tend to prefer not using the `new` keyword for purely indoctrinated reasons, but I don't feel strongly on this subject.
2. I almost always use parenthesis in arrow functions for similar reasons to using semi-colons; I recognize they add clutter and aren't necessary, but think the benefit of clarity in parsing the expression outweighs the cost. I don't feel strongly enough to say we should mandate parenthesis, but I put a vote behind preferring them.
3. Named function expressions are something I've noticed as a pattern in a lot of React codebases. I think the argument of improving readability by forcing declaration before use is a hugely good reason for using them, as the reader doesn't need to start considering the more intimate details of JS interpretation when changing/reviewing code. I'm in favor of enforcing named function expressions for this reason, and keeping our style current with the community trend (which I recognize is a futile and perhaps foolish effort.)
4. When we HAVE to use IIFE, I agree they should be wrapped as a unit, similar to my argument for using parenthesis in single argument arrow functions.
5. Purifying our functions like this is a noble goal, and I think we should do so at all where possible. That said, I recognize adhering to this is not always as clean in Ember as it is in a framework like React + Refux which strives so strongly to be functional and immutable, which I know ArBnB uses and based a lot of their style choices on. There are edge cases where I think absolutely pure functions make the code far more confusing and complex and outweighs its possible benefit. I could go either way here whether being strict or not, but certainly we should prefer wherever feasible to be pure.
6. Immutability is good. In general `forEach` and `map` should almost always be preferred. There are enough lodash methods that are pure that I agree we never should truly have to use the ES6 iterators.
7. I personally think blocks should always have new line. This is just a stylistic preference that I think aids in parsing. Switching mentally where to expect the assertion in a conditional to end and the expression to begin (same line or new line) feels unnecessary for just saving a line.
8. I think boolean conditions should force new lines as they deepen (for instance AND(OR(1, 2) OR (1,2)), 1) ), the shallow AND should be on new lines. Basically whenever a layer of boolean logic is added, indent similar to deeply nested IF's. Just personal preference. I don't know if we need to enforce this, there is a lot of grey area for where the right point between readability and neatness is.
9. I've settled on 120 for max line length in my editor. Exception is for strings. I would be hesitant to go much farther below that as an enforced standard.
10. I like what you suggested on my most recent PR: no leading underscores inside of an Ember class, but outside is fine. I see the underscores as something of a relic from stricter OOP programs though that don't make a ton of sense within Ember. It doesn't particularly bother me when I see them, but I don't think they really serve a purpose the same way they do in something like Java.
9.
